// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/quick-start":{"path":"guide/quick-start","id":"docs/guide/quick-start","parentId":"DocLayout"},"docs/components/index":{"path":"components","id":"docs/components/index","parentId":"DocLayout"},"docs/guide/releases":{"path":"guide/releases","id":"docs/guide/releases","parentId":"DocLayout"},"docs/guide/dev":{"path":"guide/dev","id":"docs/guide/dev","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Button/index":{"id":"components/Button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"components/IconStar/index":{"id":"components/IconStar/index","path":"components/icon-star","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/thomas/Desktop/Sun/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.10.0_@types+react@19.2.2_@t_ixj7fvguswg4kluuwwyp6aai4i/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/thomas/Desktop/Sun/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/thomas/Desktop/Sun/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.10.0_@types+react@19.2.2_@t_ixj7fvguswg4kluuwwyp6aai4i/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/quick-start': React.lazy(() => import(/* webpackChunkName: "docs__guide__quick-start.md" */'/Users/thomas/Desktop/Sun/docs/guide/quick-start.md')),
'docs/components/index': React.lazy(() => import(/* webpackChunkName: "docs__components__index.md" */'/Users/thomas/Desktop/Sun/docs/components/index.md')),
'docs/guide/releases': React.lazy(() => import(/* webpackChunkName: "docs__guide__releases.md" */'/Users/thomas/Desktop/Sun/docs/guide/releases.md')),
'docs/guide/dev': React.lazy(() => import(/* webpackChunkName: "docs__guide__dev.md" */'/Users/thomas/Desktop/Sun/docs/guide/dev.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/thomas/Desktop/Sun/docs/index.md')),
'components/Button/index': React.lazy(() => import(/* webpackChunkName: "packages__ui__src__Button__index.md" */'/Users/thomas/Desktop/Sun/packages/ui/src/Button/index.md')),
'components/IconStar/index': React.lazy(() => import(/* webpackChunkName: "packages__icons__src__IconStar__index.md" */'/Users/thomas/Desktop/Sun/packages/icons/src/IconStar/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/thomas/Desktop/Sun/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.10.0_@types+react@19.2.2_@t_ixj7fvguswg4kluuwwyp6aai4i/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
